# Pandas

-  2차원 데이터를 처리
-  파이썬의 엑셀의 기능을 담당

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

## 생성

In [2]:
data = {
    "Name" : ["Jackson", " Emma", "James"],
    "Weight" : [68, 74, 78],
    "Option" : [True,False,True],
    "Type": ["A", "B", "A"]
}

df = pd.DataFrame(data)
df

      Name  Weight  Option Type
0  Jackson      68    True    A
1     Emma      74   False    B
2    James      78    True    A

In [3]:
sr = df["Name"]
sr

0    Jackson
1       Emma
2      James
Name: Name, dtype: object

In [4]:
df["Weight"]

0    68
1    74
2    78
Name: Weight, dtype: int64

## 파일에서 로딩

In [6]:
df = pd.read_csv("penguins.csv")
df

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Body Mass(g),Sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [7]:
df.shape

(344, 7)

In [8]:
df["Species"]

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: Species, Length: 344, dtype: object

In [9]:
df.columns

Index(['Species', 'Island', 'Culmen Length(mm)', 'Culmen Depth(mm)',
       'Flipper Length(mm)', 'Body Mass(g)', 'Sex'],
      dtype='object')

In [10]:
df[ 'Culmen Length(mm)'][0]

np.float64(39.1)

In [11]:
df.head()

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Body Mass(g),Sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [12]:
df.iloc[0:5]

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Body Mass(g),Sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [20]:
df.loc[0:5, "Culmen Length(mm)"]

0    39.1
1    39.5
2    40.3
3     NaN
4    36.7
5    39.3
Name: Culmen Length(mm), dtype: float64

In [21]:
df.loc[ df['Culmen Length(mm)']>40, 'Culmen Length(mm)']

2      40.3
9      42.0
12     41.1
17     42.5
19     46.0
       ...
338    47.2
340    46.8
341    50.4
342    45.2
343    49.9
Name: Culmen Length(mm), Length: 242, dtype: float64

In [22]:
df.head()

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Body Mass(g),Sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

전체 데이터에서 body mass가 3800보다 큰 데이터의 "SEX"과 "BODY MASS"를 표시하세요.

In [25]:
tmp = df.loc[df['Body Mass(g)']>3800, ['Body Mass(g)',"Sex"]]

In [26]:
tmp

     Body Mass(g)     Sex
7          4675.0    MALE
9          4250.0     NaN
14         4400.0    MALE
17         4500.0    MALE
19         4200.0    MALE
..            ...     ...
338        4925.0  FEMALE
340        4850.0  FEMALE
341        5750.0    MALE
342        5200.0  FEMALE
343        5400.0    MALE

[201 rows x 2 columns]

## 컬럼 추가,삭제

In [27]:
df["Body_Mass_kg"] = df["Body Mass(g)"] / 1000

In [31]:
df = df.drop("Body Mass(g)",axis = 1)

## 결측치(Missing Value)

In [32]:
df.isna()

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Sex,Body_Mass_kg
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [33]:
df["Sex"].value_counts()

Sex
MALE      168
FEMALE    165
.           1
Name: count, dtype: int64

In [34]:
df["Sex"].isna().sum()

np.int64(10)

-  성별 컬럼에 "." 이라고 기록된 행을 표시하세요. df.loc[]을 사용할 수 있습니다.

In [35]:
df.loc[df["Sex"]==".",:]

,Species,Island,Culmen Length(mm),Culmen Depth(mm),Flipper Length(mm),Sex,Body_Mass_kg
336,Gentoo,Biscoe,44.5,15.7,217.0,.,4.875

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Species             344 non-null    object
 1   Island              344 non-null    object
 2   Culmen Length(mm)   342 non-null    float64
 3   Culmen Depth(mm)    342 non-null    float64
 4   Flipper Length(mm)  342 non-null    float64
 5   Sex                 334 non-null    object
 6   Body_Mass_kg        342 non-null    float64
dtypes: float64(4), object(3)
memory usage: 18.9+ KB